---
title: "Untitled"
author: "Alex Han"
date: "5/17/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(reshape2)
```

```{r}
p1_8_9    =     read.csv("~/git/stats-thesis/results/8_9/3/oneSided_pooled_0.025.csv")
p2_8_9    =     read.csv("~/git/stats-thesis/results/8_9/3/twoSided_pooled_0.05.csv")
u1_8_9    =     read.csv("~/git/stats-thesis/results/8_9/3/oneSided_unpooled_0.025.csv")
u2_8_9    =     read.csv("~/git/stats-thesis/results/8_9/3/twoSided_unpooled_0.05.csv")
ns1_8_9   =     read.csv("~/git/stats-thesis/results/8_9/3/ns_oneSided_0.025.csv")
ns2_8_9   =     read.csv("~/git/stats-thesis/results/8_9/3/ns_twoSided_0.05.csv")

p1_15_5   =    read.csv("~/git/stats-thesis/results/15_5/3/oneSided_pooled_0.025.csv")
p2_15_5   =    read.csv("~/git/stats-thesis/results/15_5/3/twoSided_pooled_0.05.csv")
u1_15_5   =    read.csv("~/git/stats-thesis/results/15_5/3/oneSided_unpooled_0.025.csv")
u2_15_5   =    read.csv("~/git/stats-thesis/results/15_5/3/twoSided_unpooled_0.05.csv")
ns1_15_5  =    read.csv("~/git/stats-thesis/results/15_5/3/ns_oneSided_0.025.csv")
ns2_15_5  =    read.csv("~/git/stats-thesis/results/15_5/3/ns_twoSided_0.05.csv")

p1_100_50  = read.csv("~/git/stats-thesis/results/100_50/3/oneSided_pooled_0.025.csv")
p2_100_50  = read.csv("~/git/stats-thesis/results/100_50/3/twoSided_pooled_0.05.csv")
u1_100_50  = read.csv("~/git/stats-thesis/results/100_50/3/oneSided_unpooled_0.025.csv")
u2_100_50  = read.csv("~/git/stats-thesis/results/100_50/3/twoSided_unpooled_0.05.csv")
ns1_100_50 = read.csv("~/git/stats-thesis/results/100_50/3/ns_oneSided_0.025.csv")
ns2_100_50 = read.csv("~/git/stats-thesis/results/100_50/3/ns_twoSided_0.05.csv")

B = 100
S = length(sizes)  # 3
C = length(citypes) # 6

# df = setNames(data.frame(matrix(ncol = 3, nrow = 800)), c("CI.Type", "Sample.Sizes", "Coverage"))
# sizes = c("(8, 9)", "(15, 5)")
df = setNames(data.frame(matrix(ncol = S, nrow = B*S*C)), c("CI.Type", "Sample.Sizes", "Coverage"))
sizes = c("(8, 9)", "(15, 5)", "(100, 50)")
citypes = c("p1", "p2", "u1", "u2", "ns1", "ns2")

coverageDf = matrix(nrow = S*C, ncol = B)
coverageDf[1, ] = p1_8_9$prob
coverageDf[2, ] = p2_8_9$prob
coverageDf[3, ] = u1_8_9$prob
coverageDf[4, ] = u2_8_9$prob
coverageDf[5, ] = ns1_8_9$prob
coverageDf[6, ] = ns2_8_9$prob

coverageDf[7, ]  = p1_15_5$prob
coverageDf[8, ]  = p2_15_5$prob
coverageDf[9, ]  = u1_15_5$prob
coverageDf[10, ] = u2_15_5$prob
coverageDf[11, ] = ns1_15_5$prob
coverageDf[12, ] = ns2_15_5$prob

coverageDf[13, ] = p1_100_50$prob
coverageDf[14, ] = p2_100_50$prob
coverageDf[15, ] = u1_100_50$prob
coverageDf[16, ] = u2_100_50$prob
coverageDf[17, ] = ns1_100_50$prob
coverageDf[18, ] = ns2_100_50$prob

for (i in 1:S) {    # (8, 9), (15, 5), (100, 50)
  start_row = B * C * (i-1)
  for (j in 1:C) {  # p1, p2, u1, u2
    offset = B * (j-1)
    for (k in 1:B) {
      df[start_row + offset + k, "CI.Type"] = citypes[j]
      df[start_row + offset + k, "Sample.Sizes"] = sizes[i]
      df[start_row + offset + k, "Coverage"] = coverageDf[i * j, k]
    }
  }
}

df$Sample.Sizes <- factor(df$Sample.Sizes, levels = sizes)
df$CI.Type <- factor(df$CI.Type, levels = citypes)
```


```{r}
ggplot(df, aes(x=CI.Type, y=Coverage, fill=Sample.Sizes)) + 
    geom_boxplot(alpha=0.6, key_glyph = draw_key_rect) +
    scale_fill_brewer(palette="Dark2")
```

```{r}
p1_8_9    =    read.csv("~/git/stats-thesis/results/8_9/2/oneSided_pooled_0.025.csv")
p2_8_9    =    read.csv("~/git/stats-thesis/results/8_9/2/twoSided_pooled_0.05.csv")
u1_8_9    =    read.csv("~/git/stats-thesis/results/8_9/2/oneSided_unpooled_0.025.csv")
u2_8_9    =    read.csv("~/git/stats-thesis/results/8_9/2/twoSided_unpooled_0.05.csv")

p1_15_5   =   read.csv("~/git/stats-thesis/results/15_5/2/oneSided_pooled_0.025.csv")
p2_15_5   =   read.csv("~/git/stats-thesis/results/15_5/2/twoSided_pooled_0.05.csv")
u1_15_5   =   read.csv("~/git/stats-thesis/results/15_5/2/oneSided_unpooled_0.025.csv")
u2_15_5   =   read.csv("~/git/stats-thesis/results/15_5/2/twoSided_unpooled_0.05.csv")

p1_100_50 = read.csv("~/git/stats-thesis/results/100_50/2/oneSided_pooled_0.025.csv")
p2_100_50 = read.csv("~/git/stats-thesis/results/100_50/2/twoSided_pooled_0.05.csv")
u1_100_50 = read.csv("~/git/stats-thesis/results/100_50/2/oneSided_unpooled_0.025.csv")
u2_100_50 = read.csv("~/git/stats-thesis/results/100_50/2/twoSided_unpooled_0.05.csv")

# df = setNames(data.frame(matrix(ncol = 3, nrow = 800)), c("CI.Type", "Sample.Sizes", "Coverage"))
# sizes = c("(8, 9)", "(15, 5)")
df = setNames(data.frame(matrix(ncol = 3, nrow = 1200)), c("CI.Type", "Sample.Sizes", "Coverage"))
sizes = c("(8, 9)", "(15, 5)", "(100, 50)")
citypes = c("p1", "p2", "u1", "u2")

coverageDf = matrix(nrow = 12, ncol = 100)
coverageDf[1, ] = p1_8_9$prob
coverageDf[2, ] = p2_8_9$prob
coverageDf[3, ] = u1_8_9$prob
coverageDf[4, ] = u2_8_9$prob

coverageDf[5, ] = p1_15_5$prob
coverageDf[6, ] = p2_15_5$prob
coverageDf[7, ] = u1_15_5$prob
coverageDf[8, ] = u2_15_5$prob

coverageDf[9, ]  = p1_100_50$prob
coverageDf[10, ] = p2_100_50$prob
coverageDf[11, ] = u1_100_50$prob
coverageDf[12, ] = u2_100_50$prob

for (i in 1:3) {    # (8, 9), (15, 5), (100, 50)
  start_row = 400 * (i-1)
  for (j in 1:4) {  # p1, p2, u1, u2
    offset = 100 * (j-1)
    
    for (k in 1:100) {
      df[start_row + offset + k, "CI.Type"] = citypes[j]
      df[start_row + offset + k, "Sample.Sizes"] = sizes[i]
      df[start_row + offset + k, "Coverage"] = coverageDf[i * j, k]
    }
  }
}

df$Sample.Sizes <- factor(df$Sample.Sizes, levels = sizes)

ggplot(df, aes(x=CI.Type, y=Coverage, fill=Sample.Sizes)) + 
    geom_boxplot(alpha=0.5, key_glyph = draw_key_rect) +
    scale_fill_brewer(palette="Dark2")
```


```{r}
ns1_100_50$prob
```

